Repository kubesphere/prow-tutorial, pull requests merged in 2019-08, with the labels that each got.

#6 add ks-ci-bot config
  ks-ci-bot/OWNERS
  ks-ci-bot/README.md
  ks-ci-bot/config.yaml
  ks-ci-bot/label-cron-job.yaml
  ks-ci-bot/labels.yaml
  ks-ci-bot/plugins.yaml
Labels: approved, lgtm

#8 migrate prow
  ks-ci-bot/config.yaml
  ks-ci-bot/plugins.yaml
Labels: approved, lgtm, size/M

#9 test prow
  ks-ci-bot/OWNERS
Labels: approved, lgtm, size/XS

#10 add labels
  ks-ci-bot/label-cron-job.yaml
  ks-ci-bot/labels.yaml
Labels: approved, lgtm, size/S

#11 change eip
  ks-ci-bot/README.md
  ks-ci-bot/config.yaml
Labels: approved, lgtm, size/S

#12 Pr for demo
  jobs.md
Labels: approved, kind/feature, lgtm, size/XS
