Repository kubesphere/prow-tutorial, pull requests merged in 2021-05, with the labels that each got.

#34 Add linuxsuren as a owner of the directory ks-ci-bot
  .gitignore
  ks-ci-bot/OWNERS
Labels: dco-signoff: yes, size/XS

#35 Add GitHub project set for kubesphere/website
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#36 Add prow plugin stage
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#38 Add repo s2i-nodejs-container
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#37 Add repo kubesphere/image-sync-config
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#39 Add more devops related projects
  ks-ci-bot/OWNERS
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#40 Add s2i-java-container repo into config.yaml
  ks-ci-bot/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#42 Comment the useless presubmits
  ks-ci-bot/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#43 Add s2i-java-runtimeImag into the repo list
  ks-ci-bot/config.yaml
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#44 Add repo to tide query
  ks-ci-bot/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
