Repository kubesphere/prow-tutorial, pull requests merged in 2021-01, with the labels that each got.

#18 feature: config milestone
  ks-ci-bot/config.yaml
  ks-ci-bot/plugins.yaml
  ks-ci-bot/update.sh
Labels: approved, dco-signoff: yes, size/S

#19 feature: add project
  ks-ci-bot/config.yaml
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, size/M

#22 Parts of console issues might be belong to DevOps project
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#23 Add help plugin for add help labels
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#20 Add ks-jenkins into prow
  ks-ci-bot/config.yaml
  ks-ci-bot/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
